#!/command/with-contenv bash
set -e
IP="${ADVERTISED_IP}"
if [ -z "$IP" ] || [ "$IP" = "0.0.0.0" ]; then
  echo "FATAL: ADVERTISED_IP non valido: '$IP'" >&2
  exit 1
fi

exec rtpengine \
  --interface=${IP} \
  --listen-ng=127.0.0.1:22222 \
  --port-min=49000 --port-max=50000 \
  --log-level=4 \
  --timeout=60 \
  --dtls-passive
